"""Unit tests for HTML renderer.

Note: The HtmlRenderer now only creates placeholder files for archive date
tracking. The actual HTML content is generated by the Vue SPA frontend.
These tests verify the placeholder file creation behavior.
"""

import tempfile
from collections.abc import Generator
from datetime import UTC, datetime
from pathlib import Path

import pytest

from src.features.config.schemas.base import LinkType
from src.linker.models import Story, StoryLink
from src.renderer.html_renderer import HtmlRenderer
from src.renderer.metrics import RendererMetrics
from src.renderer.models import (
    RenderContext,
    RenderManifest,
    RunInfo,
    SourceStatus,
    SourceStatusCode,
)


@pytest.fixture
def temp_output_dir() -> Generator[Path]:
    """Create a temporary output directory."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def sample_story() -> Story:
    """Create a sample story for testing."""
    return Story(
        story_id="test-story-1",
        title="Test Story Title",
        primary_link=StoryLink(
            url="https://example.com/article",
            link_type=LinkType.OFFICIAL,
            source_id="test-source",
            tier=0,
            title="Test Story Title",
        ),
        links=[
            StoryLink(
                url="https://example.com/article",
                link_type=LinkType.OFFICIAL,
                source_id="test-source",
                tier=0,
                title="Test Story Title",
            ),
        ],
        entities=["openai"],
        published_at=datetime(2026, 1, 15, 10, 0, 0, tzinfo=UTC),
    )


@pytest.fixture
def sample_context(sample_story: Story) -> RenderContext:
    """Create sample render context."""
    return RenderContext(
        run_id="test-run",
        run_date="2026-01-15",
        generated_at="2026-01-15T10:00:00Z",
        timezone="UTC",
        top5=[sample_story],
        model_releases_by_entity={"openai": [sample_story]},
        papers=[],
        radar=[],
        sources_status=[
            SourceStatus(
                source_id="test-source",
                name="Test Source",
                status=SourceStatusCode.HAS_UPDATE,
            )
        ],
        recent_runs=[
            RunInfo(
                run_id="test-run",
                started_at=datetime(2026, 1, 15, 9, 0, 0, tzinfo=UTC),
                finished_at=datetime(2026, 1, 15, 9, 5, 0, tzinfo=UTC),
                success=True,
            )
        ],
        archive_dates=["2026-01-15", "2026-01-14"],
    )


class TestHtmlRenderer:
    """Tests for HtmlRenderer.

    Note: HtmlRenderer now only creates placeholder files for archive date
    tracking. The actual HTML pages are generated by the Vue SPA frontend.
    """

    def test_render_creates_placeholder_file(
        self,
        temp_output_dir: Path,
        sample_context: RenderContext,
    ) -> None:
        """Render creates placeholder file in day/ directory."""
        RendererMetrics.reset()
        manifest = RenderManifest(
            run_id="test",
            run_date="2026-01-15",
            generated_at="2026-01-15T10:00:00Z",
        )

        renderer = HtmlRenderer(run_id="test", output_dir=temp_output_dir)
        renderer.render(sample_context, manifest)

        # Verify placeholder file was created
        placeholder_path = temp_output_dir / "day" / "2026-01-15.html"
        assert placeholder_path.is_file()

    def test_render_creates_directories(
        self,
        temp_output_dir: Path,
        sample_context: RenderContext,
    ) -> None:
        """Render creates required directories."""
        RendererMetrics.reset()
        manifest = RenderManifest(
            run_id="test",
            run_date="2026-01-15",
            generated_at="2026-01-15T10:00:00Z",
        )

        renderer = HtmlRenderer(run_id="test", output_dir=temp_output_dir)
        renderer.render(sample_context, manifest)

        # Verify directories were created
        assert temp_output_dir.is_dir()
        assert (temp_output_dir / "day").is_dir()

    def test_placeholder_content(
        self,
        temp_output_dir: Path,
        sample_context: RenderContext,
    ) -> None:
        """Placeholder file contains expected comment."""
        RendererMetrics.reset()
        manifest = RenderManifest(
            run_id="test",
            run_date="2026-01-15",
            generated_at="2026-01-15T10:00:00Z",
        )

        renderer = HtmlRenderer(run_id="test", output_dir=temp_output_dir)
        renderer.render(sample_context, manifest)

        content = (temp_output_dir / "day" / "2026-01-15.html").read_text()
        assert "Placeholder" in content
        assert "2026-01-15" in content
        assert "Vue SPA" in content

    def test_render_with_different_dates(
        self,
        temp_output_dir: Path,
    ) -> None:
        """Can render placeholders for different dates."""
        RendererMetrics.reset()

        for run_date in ["2026-01-10", "2026-01-11", "2026-01-12"]:
            context = RenderContext(
                run_id="test",
                run_date=run_date,
                generated_at=f"{run_date}T10:00:00Z",
            )

            manifest = RenderManifest(
                run_id="test",
                run_date=run_date,
                generated_at=f"{run_date}T10:00:00Z",
            )

            renderer = HtmlRenderer(run_id="test", output_dir=temp_output_dir)
            renderer.render(context, manifest)

            assert (temp_output_dir / "day" / f"{run_date}.html").is_file()

    def test_no_tmp_files_left(
        self,
        temp_output_dir: Path,
        sample_context: RenderContext,
    ) -> None:
        """No .tmp files left after render."""
        RendererMetrics.reset()
        manifest = RenderManifest(
            run_id="test",
            run_date="2026-01-15",
            generated_at="2026-01-15T10:00:00Z",
        )

        renderer = HtmlRenderer(run_id="test", output_dir=temp_output_dir)
        renderer.render(sample_context, manifest)

        # Check no .tmp files exist
        tmp_files = list(temp_output_dir.rglob("*.tmp"))
        assert len(tmp_files) == 0

    def test_metrics_recorded(
        self,
        temp_output_dir: Path,
        sample_context: RenderContext,
    ) -> None:
        """Render records duration metrics."""
        RendererMetrics.reset()
        manifest = RenderManifest(
            run_id="test",
            run_date="2026-01-15",
            generated_at="2026-01-15T10:00:00Z",
        )

        renderer = HtmlRenderer(run_id="test", output_dir=temp_output_dir)
        renderer.render(sample_context, manifest)

        metrics = RendererMetrics.get_instance()
        # Should have recorded a duration > 0
        assert metrics._html_render_ms > 0
