"""Data models for weekly and monthly paper reports."""

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


ReportType = Literal["weekly", "monthly"]


def _default_latest_reports() -> dict[str, str | None]:
    """Return an empty latest-report index by report type."""
    return {"weekly": None, "monthly": None}


class ReportDigest(BaseModel):
    """JSON payload for a generated weekly or monthly report."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    report_type: ReportType
    period_id: Annotated[str, Field(min_length=1)]
    title: Annotated[str, Field(min_length=1)]
    summary: str | None = None
    timezone: Annotated[str, Field(min_length=1)]
    period_start: Annotated[str, Field(pattern=r"^\d{4}-\d{2}-\d{2}$")]
    period_end: Annotated[str, Field(pattern=r"^\d{4}-\d{2}-\d{2}$")]
    generated_at: Annotated[str, Field(min_length=1)]
    covered_dates: list[str] = Field(default_factory=list)
    missing_dates: list[str] = Field(default_factory=list)
    source_files: list[str] = Field(default_factory=list)
    items_considered: Annotated[int, Field(ge=0)] = 0
    stories_considered: Annotated[int, Field(ge=0)] = 0
    recommendations: list[dict[str, Any]] = Field(default_factory=list)
    blog_items_considered: Annotated[int, Field(ge=0)] = 0
    blog_stories_considered: Annotated[int, Field(ge=0)] = 0
    blog_recommendations: list[dict[str, Any]] = Field(default_factory=list)
    selection_policy: dict[str, Any] = Field(default_factory=dict)


class ReportIndexEntry(BaseModel):
    """Compact index entry for a generated report."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    report_type: ReportType
    period_id: Annotated[str, Field(min_length=1)]
    title: Annotated[str, Field(min_length=1)]
    summary: str | None = None
    period_start: Annotated[str, Field(pattern=r"^\d{4}-\d{2}-\d{2}$")]
    period_end: Annotated[str, Field(pattern=r"^\d{4}-\d{2}-\d{2}$")]
    generated_at: Annotated[str, Field(min_length=1)]
    path: Annotated[str, Field(min_length=1)]
    recommendation_count: Annotated[int, Field(ge=0)] = 0
    blog_recommendation_count: Annotated[int, Field(ge=0)] = 0
    missing_dates: list[str] = Field(default_factory=list)


class ReportIndex(BaseModel):
    """Index payload for all generated reports."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    generated_at: Annotated[str, Field(min_length=1)]
    latest: dict[str, str | None] = Field(default_factory=_default_latest_reports)
    weekly: list[ReportIndexEntry] = Field(default_factory=list)
    monthly: list[ReportIndexEntry] = Field(default_factory=list)


class ReportMetadata(BaseModel):
    """Editable report metadata generated by AI or local fallback logic."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    title: str | None = None
    summary: str | None = None
    source: Literal["ai", "fallback"] = "ai"
