"""HTML renderer - creates placeholder files for archive date tracking."""

import time
from pathlib import Path

import structlog

from src.renderer.metrics import RendererMetrics
from src.renderer.models import (
    RenderContext,
    RenderManifest,
)


logger = structlog.get_logger()


class HtmlRenderer:
    """Creates placeholder HTML files for archive date tracking.

    The actual HTML content is generated by the Vue SPA build process.
    This class only creates placeholder files so that archive_dates
    can be detected by scanning the day/ directory.
    """

    def __init__(
        self,
        run_id: str,
        output_dir: Path,
        metrics: RendererMetrics | None = None,
    ) -> None:
        """Initialize the HTML renderer.

        Args:
            run_id: Unique run identifier.
            output_dir: Output directory for rendered files.
            metrics: Optional metrics instance.
        """
        self._run_id = run_id
        self._output_dir = output_dir
        self._metrics = metrics or RendererMetrics.get_instance()
        self._log = logger.bind(run_id=run_id, component="renderer")

    def render(self, context: RenderContext, manifest: RenderManifest) -> None:  # noqa: ARG002
        """Create placeholder HTML file for archive date tracking.

        The placeholder file will be replaced by the Vue SPA index.html
        during the CI/CD build process.

        Args:
            context: Render context with data for templates.
            manifest: Manifest to record generated files (unused, kept for API compatibility).
        """
        start_time = time.perf_counter()

        # Ensure directories exist
        self._output_dir.mkdir(parents=True, exist_ok=True)
        day_dir = self._output_dir / "day"
        day_dir.mkdir(parents=True, exist_ok=True)

        # Create placeholder file for this date
        placeholder_path = day_dir / f"{context.run_date}.html"
        placeholder_content = (
            f"<!-- Placeholder for {context.run_date} - replaced by Vue SPA -->\n"
        )
        placeholder_path.write_text(placeholder_content)

        self._log.info(
            "placeholder_created",
            run_date=context.run_date,
            path=str(placeholder_path),
        )

        duration_ms = (time.perf_counter() - start_time) * 1000
        self._metrics.record_html_duration(duration_ms)
